// Copyright 2026 Candace Labs
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Which changed files are generated code, and so never part of a task's
//! reference fix or its churn.
//!
//! A file is generated when any rule fires, checked in this order:
//!
//! | rule | fires when |
//! |---|---|
//! | `cgen_name` | the file stem ends in `_cgen` (CSF's CandaceCodegen outputs) |
//! | `heuristic` | the path matches the miner's long-standing list ([`crate::GENERATED`]) |
//! | `csf_generated_path` | the path is, or lies under, a `generated` root a CSF model declares |
//! | `generated_header` | one of its first [`HEADER_LINES`] lines reads `Code generated ... DO NOT EDIT` (Go's convention; CSF's banner follows it) |

use super::under;
use regex::Regex;
use std::sync::OnceLock;

/// How many leading lines are searched for the generated-code notice.
pub const HEADER_LINES: usize = 5;

fn header_re() -> &'static Regex {
    static RE: OnceLock<Regex> = OnceLock::new();
    RE.get_or_init(|| Regex::new(r"Code generated .*DO NOT EDIT").expect("static regex"))
}

pub fn is_cgen(path: &str) -> bool {
    let name = path.rsplit('/').next().unwrap_or(path);
    let stem = name.split_once('.').map(|(s, _)| s).unwrap_or(name);
    stem.ends_with("_cgen")
}

pub fn has_generated_header(bytes: &[u8]) -> bool {
    String::from_utf8_lossy(bytes).lines().take(HEADER_LINES).any(|l| header_re().is_match(l))
}

/// The rule that makes `path` generated, if any. `header` is asked for the
/// file's bytes only when the cheaper path rules do not decide.
pub fn why_generated(path: &str, declared: &[String], header: impl FnOnce() -> Option<Vec<u8>>)
    -> Option<&'static str> {
    if is_cgen(path) {
        Some("cgen_name")
    } else if crate::GENERATED.iter().any(|g| path.contains(g)) {
        Some("heuristic")
    } else if declared.iter().any(|d| under(path, d)) {
        Some("csf_generated_path")
    } else if header().is_some_and(|b| has_generated_header(&b)) {
        Some("generated_header")
    } else {
        None
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const CSF_BANNER: &str = "(* //////////////////////////////////////////////////////////// *)\n\
        (* Code generated by CandaceCodegen v0.1.0-dev; the _cgen suffix marks generated files. DO NOT EDIT. *)\n";

    #[test]
    fn each_rule_fires_alone() {
        let none = || None;
        assert_eq!(why_generated("api/x.pb.go", &[], none), Some("heuristic"));
        assert_eq!(why_generated("csf/api_cgen.go", &[], none), Some("cgen_name"));
        assert!(is_cgen("csf/model_cgen.ml") && is_cgen("a/b_cgen.pb.go") && !is_cgen("a/cgen.go")
                && !is_cgen("a_cgen/x.go"));
        let declared = vec!["svc/internal/db".to_string()];
        assert_eq!(why_generated("svc/internal/db/models.go", &declared, none), Some("csf_generated_path"));
        assert_eq!(why_generated("svc/internal/dbx/models.go", &declared, none), None, "prefix ends at a /");
        let go = b"// Code generated by sqlc. DO NOT EDIT.\n// versions:\npackage db\n".to_vec();
        assert_eq!(why_generated("svc/store/models.go", &[], || Some(go)), Some("generated_header"));
        assert_eq!(why_generated("svc/x.ml", &[], || Some(CSF_BANNER.as_bytes().to_vec())),
                   Some("generated_header"));
        assert_eq!(why_generated("svc/x.go", &[], || Some(b"package x\n".to_vec())), None);
        assert_eq!(why_generated("svc/deleted.go", &[], none), None, "no bytes, no header");
    }

    #[test]
    fn the_notice_must_be_in_the_first_lines_and_on_one_line() {
        let late = format!("{}// Code generated by x. DO NOT EDIT.\n", "//\n".repeat(HEADER_LINES));
        assert!(!has_generated_header(late.as_bytes()));
        assert!(!has_generated_header(b"// Code generated by x.\n// DO NOT EDIT.\n"));
        assert!(!has_generated_header(b"// This mentions DO NOT EDIT only.\n"));
    }

    #[test]
    fn the_cheap_rules_decide_before_the_file_is_read() {
        let mut read = false;
        assert_eq!(why_generated("a/b_cgen.rs", &[], || { read = true; None }), Some("cgen_name"));
        assert!(!read);
    }
}
